import React from 'react';
import Button from "../Button"
import { IconArrowUpRight } from "@tabler/icons-react"

const downloadLinks = [
  {
    link: 'https://forest-archive.chainsafe.dev/list/calibnet/diff',
    title: 'Calibration Testnet Diff-Snapshots',
  },
  {
    link: 'https://forest-archive.chainsafe.dev/list/calibnet/lite',
    title: 'Calibration Testnet Lite-Snapshots',
  },
  {
    link: 'https://forest-archive.chainsafe.dev/list/mainnet/diff',
    title: 'Filecoin Mainnet Diff-Snapshots',
  },
  {
    link: 'https://forest-archive.chainsafe.dev/list/mainnet/lite',
    title: 'Filecoin Mainnet Lite-Snapshots',
  },
]

export default function DownloadArchive() {
  return (
<div className="relative h-full w-full">
  <div className="relative flex flex-col justify-center pt-8 pb-6 px-8">
    <div className="grid md:grid-cols-3 py-4">
        <div className='flex flex-col md:col-span-2'>
        <h1 className='mt-7 text-neutral-200 text-2xl font-normal'>
          Forest Archive
          </h1>
          <h2 className='mt-3 md:max-w-[500px] text-neutral-300 text-lg leading-6 font-normal'>
            The entire archive of the Filecoin history was generated by Forest and is available for download free of charge. The archive is split into multiple snapshots, which can be joined together to form a complete history of the network.
          </h2>
        </div>
        <div className='grid grid-cols-2 gap-x-1 gap-y-1'>
          {downloadLinks.map((card, index) => (
            <a href={card.link} key={index} className='transition-all py-4 flex flex-col justify-start px-4 bg-neutral-900 rounded-2xl cursor-pointer hover:brightness-75' rel="noopener noreferrer" target="_blank">
              <div className='flex justify-between'>
                <Button href={card.link} type="link"><IconArrowUpRight stroke={1.5} className="text-brand-400" width={24}/></Button>
              </div>
              <h3 className='mt-8 text-gray-200 text-xl leading-7'>{card.title}</h3>
            </a>
          ))}
        </div>
      </div>
    </div>
    </div>
  )
}
