name: Link Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "00 9 * * *"
  push:
    branches:
      - main
  merge_group:
  pull_request:
    branches:
      - main

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: --base . --verbose --no-progress './**/*.md' './**/*.html' './**/*.rst' './**/*.tsx'

      - name: Create Issue From File
        if: env.lychee_exit_code != 0 && github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: automated issue

      - name: Fail job on error
        if: env.lychee_exit_code != 0 && github.event_name != 'schedule'
        run: exit 1
